{"success": true, "code": 0, "requestId": null, "resubmitToken": null, "msg": null,
 "content": {"pageNo": 1, "pageSize": 15, "positionResult":
   {"totalCount": 5000, "pageSize": 15,
             "locationInfo": {"city": "北京", "district": null,"businessZone": null}, "result": [
         {"calcScore": false, "createTime": "2016-06-23 00:57:19", "companyId": 25592, "companyName": "新浪网",
          "positionName": "内容编辑", "positionType": "编辑", "workYear": "不限", "education": "本科", "jobNature": "全职",
          "companyShortName": "新浪网技术（中国）有限公司", "city": "北京", "salary": "4k-6k", "financeStage": "上市公司",
          "positionId": 1521760, "companyLogo": "image1/M00/00/35/Cgo8PFTUXJeAJhm5AAAyDX2QCwc674.jpg",
          "positionFirstType": "运营", "positionAdvantage": "高尔夫头号资讯门户，行业入门最佳渠道", "approve": 1, "industryField": "文化娱乐",
          "district": "海淀区", "score": 0, "companyLabelList": ["免费班车", "岗位晋升", "五险一金", "定期体检"], "deliverCount": 14,
          "leaderName": "暂没有填写", "companySize": "2000人以上", "countAdjusted": false, "relScore": 0, "adjustScore": 0,
          "showOrder": 0, "haveDeliver": false, "imstate": "disabled", "createTimeSort": 1466614639000,
          "positonTypesMap": null, "hrScore": 37, "flowScore": 0, "showCount": 126, "pvScore": 159.3366123641539,
          "plus": "否", "businessZones": ["北京大学", "中关村", "苏州街"], "publisherId": 3609876, "loginTime": 1466614645000,
          "appShow": 582, "randomScore": 0, "orderBy": 69, "formatCreateTime": "00:57发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-23 00:35:48", "companyId": 90996, "companyName": "有道理",
          "positionName": "PHP", "positionType": "后端开发", "workYear": "1年以下", "education": "学历不限", "jobNature": "全职",
          "companyShortName": "北京有道理科技传媒有限公司", "city": "北京", "salary": "16k-25k", "financeStage": "初创型(不需要融资)",
          "positionId": 2000538,
          "companyLogo": "image1/M00/44/5C/Cgo8PFXVWbeAZC7XAABn-fqssL8694.jpg?cc=0.9902268927544355",
          "positionFirstType": "技术", "positionAdvantage": "工作环境舒适 发展空间大 薪水丰厚", "approve": 0,
          "industryField": "移动互联网 · O2O", "district": "朝阳区", "score": 0,
          "companyLabelList": ["专项奖金", "股票期权", "绩效奖金", "领导好"], "deliverCount": 0, "leaderName": "孙晓岐",
          "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466613348000, "positonTypesMap": null,
          "hrScore": 13, "flowScore": 0, "showCount": 10, "pvScore": 1.4273377514643952, "plus": "否",
          "businessZones": ["百子湾", "南磨房"], "publisherId": 5218206, "loginTime": 1466613227000, "appShow": 0,
          "randomScore": 0, "orderBy": 62, "formatCreateTime": "00:35发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:55:52", "companyId": 113736, "companyName": "上善若水",
          "positionName": "WEB前端工程师", "positionType": "前端开发", "workYear": "1-3年", "education": "大专", "jobNature": "全职",
          "companyShortName": "北京上善若水会计服务有限公司", "city": "北京", "salary": "8k-15k", "financeStage": "初创型(未融资)",
          "positionId": 2000534, "companyLogo": "i/image/M00/03/2F/CgqKkVaurP6AUP7-AAUIwQ715Uc521.jpg",
          "positionFirstType": "技术", "positionAdvantage": "发展空间大，团队氛围好，有奖金，成长快", "approve": 1,
          "industryField": "企业服务 · 其他", "district": "朝阳区", "score": 0, "companyLabelList": [], "deliverCount": 0,
          "leaderName": "暂没有填写", "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 0,
          "showOrder": 0, "haveDeliver": false, "imstate": "disabled", "createTimeSort": 1466610952000,
          "positonTypesMap": null, "hrScore": 50, "flowScore": 0, "showCount": 39, "pvScore": 2.8271441100088563,
          "plus": "否", "businessZones": ["亮马桥", "三元桥", "燕莎"], "publisherId": 4583315, "loginTime": 1466610270000,
          "appShow": 0, "randomScore": 0, "orderBy": 66, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:47:58", "companyId": 34200, "companyName": "减约",
          "positionName": "市场总监", "positionType": "高端市场职位", "workYear": "3-5年", "education": "本科", "jobNature": "全职",
          "companyShortName": "北京减脂时代科技有限公司", "city": "北京", "salary": "20k-30k", "financeStage": "成长型(A轮)",
          "positionId": 1000628, "companyLogo": "i/image/M00/00/C6/CgqKkVZVW_WAIfIZAAGYnY-bzVY040.png",
          "positionFirstType": "市场与销售", "positionAdvantage": "积极健康正能量的事业期待你的加入", "approve": 1,
          "industryField": "移动互联网 · 医疗健康", "district": "朝阳区", "score": 0,
          "companyLabelList": ["技能培训", "年底双薪", "岗位晋升", "扁平管理"], "deliverCount": 29, "leaderName": "Echo",
          "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 61, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466610478000, "positonTypesMap": null,
          "hrScore": 94, "flowScore": 0, "showCount": 942, "pvScore": 28.969505498999983, "plus": "是",
          "businessZones": ["来广营", "望京"], "publisherId": 582862, "loginTime": 1466610217000, "appShow": 366,
          "randomScore": 0, "orderBy": 69, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:47:57", "companyId": 34200, "companyName": "减约",
          "positionName": "高级内容运营", "positionType": "运营", "workYear": "1-3年", "education": "本科", "jobNature": "全职",
          "companyShortName": "北京减脂时代科技有限公司", "city": "北京", "salary": "8k-15k", "financeStage": "成长型(A轮)",
          "positionId": 895664, "companyLogo": "i/image/M00/00/C6/CgqKkVZVW_WAIfIZAAGYnY-bzVY040.png",
          "positionFirstType": "运营", "positionAdvantage": "积极健康正能量的事业期待你的加入", "approve": 1,
          "industryField": "移动互联网 · 医疗健康", "district": "朝阳区", "score": 0,
          "companyLabelList": ["技能培训", "年底双薪", "岗位晋升", "扁平管理"], "deliverCount": 3, "leaderName": "Echo",
          "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 61, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466610477000, "positonTypesMap": null,
          "hrScore": 94, "flowScore": 0, "showCount": 195, "pvScore": 6.079686821800369, "plus": "是",
          "businessZones": ["来广营", "望京"], "publisherId": 582862, "loginTime": 1466610217000, "appShow": 166,
          "randomScore": 0, "orderBy": 69, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:42:53", "companyId": 112882, "companyName": "insenth",
          "positionName": "Unity3D 研发工程师", "positionType": "移动开发", "workYear": "不限", "education": "硕士",
          "jobNature": "实习", "companyShortName": "北京知境科技有限公司", "city": "北京", "salary": "5k-10k",
          "financeStage": "初创型(天使轮)", "positionId": 2000533,
          "companyLogo": "i/image/M00/02/EC/Cgp3O1ag6Y-Aa3cAAAHGkeTJHLc765.png", "positionFirstType": "技术",
          "positionAdvantage": "高期权+高福利+弹性工作", "approve": 0, "industryField": "移动互联网 · 硬件", "district": "海淀区",
          "score": 0, "companyLabelList": [], "deliverCount": 0, "leaderName": "暂没有填写", "companySize": "少于15人",
          "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0, "haveDeliver": false,
          "imstate": "today", "createTimeSort": 1466610173000, "positonTypesMap": null, "hrScore": 4, "flowScore": 0,
          "showCount": 54, "pvScore": 9.596932800986876, "plus": "否", "businessZones": null, "publisherId": 3750310,
          "loginTime": 1466615067000, "appShow": 0, "randomScore": 0, "orderBy": 62, "formatCreateTime": "1天前发布",
          "adWord": 0, "totalCount": 0, "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:40:42", "companyId": 133966, "companyName": "复诚国际教育集团",
          "positionName": "2016暑假实习生（香港）---在校生", "positionType": "投融资", "workYear": "不限", "education": "大专",
          "jobNature": "实习", "companyShortName": "上海复诚文化传播有限公司", "city": "北京", "salary": "3k-4k",
          "financeStage": "初创型(不需要融资)", "positionId": 1946245,
          "companyLogo": "i/image/M00/39/19/CgqKkVdlni2AetuvAAAPCwIEbfg208.png", "positionFirstType": "金融",
          "positionAdvantage": "实习证明、推荐信、500强人脉圈", "approve": 1, "industryField": "教育 · 移动互联网", "district": "海淀区",
          "score": 0, "companyLabelList": [], "deliverCount": 2, "leaderName": "元培", "companySize": "15-50人",
          "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0, "haveDeliver": false,
          "imstate": "disabled", "createTimeSort": 1466610042000, "positonTypesMap": null, "hrScore": 52,
          "flowScore": 0, "showCount": 89, "pvScore": 14.784655848959423, "plus": "否",
          "businessZones": ["北京大学", "颐和园", "中关村"], "publisherId": 2105112, "loginTime": 1466609767000, "appShow": 45,
          "randomScore": 0, "orderBy": 68, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:39:14", "companyId": 133966, "companyName": "复诚国际教育集团",
          "positionName": "新媒体运营/用户运营", "positionType": "运营", "workYear": "不限", "education": "本科", "jobNature": "实习",
          "companyShortName": "上海复诚文化传播有限公司", "city": "北京", "salary": "2k-4k", "financeStage": "初创型(不需要融资)",
          "positionId": 2000532, "companyLogo": "i/image/M00/39/19/CgqKkVdlni2AetuvAAAPCwIEbfg208.png",
          "positionFirstType": "运营", "positionAdvantage": "BAT Game就业、实习证明、高成长", "approve": 1,
          "industryField": "教育 · 移动互联网", "district": "海淀区", "score": 0, "companyLabelList": [], "deliverCount": 0,
          "leaderName": "元培", "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 0,
          "showOrder": 0, "haveDeliver": false, "imstate": "disabled", "createTimeSort": 1466609954000,
          "positonTypesMap": null, "hrScore": 52, "flowScore": 0, "showCount": 54, "pvScore": 3.3629793746663386,
          "plus": "否", "businessZones": ["北京大学", "颐和园", "中关村"], "publisherId": 2105112, "loginTime": 1466609767000,
          "appShow": 0, "randomScore": 0, "orderBy": 68, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:38:57", "companyId": 93925, "companyName": "凯泰铭",
          "positionName": "产品经理", "positionType": "产品经理", "workYear": "3-5年", "education": "本科", "jobNature": "全职",
          "companyShortName": "凯泰铭科技(北京)有限公司", "city": "北京", "salary": "8k-15k", "financeStage": "初创型(天使轮)",
          "positionId": 1784295, "companyLogo": "image2/M00/06/75/CgpzWlX6NRKAEAUjAABNM999VMQ023.png",
          "positionFirstType": "产品", "positionAdvantage": "独栋办公楼完美职场晋升期权项目奖金样样有", "approve": 1,
          "industryField": "移动互联网 · 其他", "district": "朝阳区", "score": 0,
          "companyLabelList": ["节日礼物", "股票期权", "带薪年假", "岗位晋升"], "deliverCount": 4, "leaderName": "王辉",
          "companySize": "50-150人", "countAdjusted": false, "relScore": 0, "adjustScore": 48, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466609937000, "positonTypesMap": null,
          "hrScore": 86, "flowScore": 0, "showCount": 276, "pvScore": 60.086652375100215, "plus": "是",
          "businessZones": ["十里堡", "四惠", "八里庄"], "publisherId": 4986588, "loginTime": 1466609068000, "appShow": 1867,
          "randomScore": 0, "orderBy": 68, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:37:13", "companyId": 126264, "companyName": "安富宝",
          "positionName": "web前端", "positionType": "前端开发", "workYear": "3-5年", "education": "本科", "jobNature": "全职",
          "companyShortName": "北京安富宝科技有限公司", "city": "北京", "salary": "15k-20k", "financeStage": "初创型(不需要融资)",
          "positionId": 1863855, "companyLogo": "i/image/M00/24/1D/Cgp3O1cZkoqAWgaZAAAT0C6l2AU179.jpg",
          "positionFirstType": "技术", "positionAdvantage": "平台好，前景优，福利多", "approve": 0, "industryField": "电子商务 · 移动互联网",
          "district": "西城区", "score": 0, "companyLabelList": ["年底双薪", "带薪年假", "交通补助", "午餐补助"], "deliverCount": 0,
          "leaderName": "暂没有填写", "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 0,
          "showOrder": 0, "haveDeliver": false, "imstate": "today", "createTimeSort": 1466609833000,
          "positonTypesMap": null, "hrScore": 64, "flowScore": 0, "showCount": 83, "pvScore": 28.56335248198469,
          "plus": "否", "businessZones": ["阜成门", "南礼士路", "月坛"], "publisherId": 4878803, "loginTime": 1466567707000,
          "appShow": 169, "randomScore": 0, "orderBy": 62, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:36:54", "companyId": 126264, "companyName": "安富宝",
          "positionName": "JavaScript", "positionType": "前端开发", "workYear": "3-5年", "education": "大专",
          "jobNature": "全职", "companyShortName": "北京安富宝科技有限公司", "city": "北京", "salary": "15k-20k",
          "financeStage": "初创型(不需要融资)", "positionId": 2000531,
          "companyLogo": "i/image/M00/24/1D/Cgp3O1cZkoqAWgaZAAAT0C6l2AU179.jpg", "positionFirstType": "技术",
          "positionAdvantage": "福利多,环境优,BOSS好", "approve": 0, "industryField": "电子商务 · 移动互联网", "district": "西城区",
          "score": 0, "companyLabelList": ["年底双薪", "带薪年假", "交通补助", "午餐补助"], "deliverCount": 0, "leaderName": "暂没有填写",
          "companySize": "15-50人", "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466609814000, "positonTypesMap": null,
          "hrScore": 27, "flowScore": 0, "showCount": 42, "pvScore": 4.724051257810356, "plus": "否",
          "businessZones": ["阜成门", "南礼士路", "月坛"], "publisherId": 5276932, "loginTime": 1466609778000, "appShow": 0,
          "randomScore": 0, "orderBy": 62, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:36:32", "companyId": 112882, "companyName": "insenth",
          "positionName": "iOS", "positionType": "移动开发", "workYear": "不限", "education": "硕士", "jobNature": "实习",
          "companyShortName": "北京知境科技有限公司", "city": "北京", "salary": "5k-10k", "financeStage": "初创型(天使轮)",
          "positionId": 2000530, "companyLogo": "i/image/M00/02/EC/Cgp3O1ag6Y-Aa3cAAAHGkeTJHLc765.png",
          "positionFirstType": "技术", "positionAdvantage": "高期权+丰富团建+弹性工作", "approve": 0, "industryField": "移动互联网 · 硬件",
          "district": "海淀区", "score": 0, "companyLabelList": [], "deliverCount": 2, "leaderName": "暂没有填写",
          "companySize": "少于15人", "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466609792000, "positonTypesMap": null,
          "hrScore": 4, "flowScore": 0, "showCount": 54, "pvScore": 16.705771912829007, "plus": "否",
          "businessZones": null, "publisherId": 3750310, "loginTime": 1466615067000, "appShow": 0, "randomScore": 0,
          "orderBy": 62, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0, "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:22:22", "companyId": 718, "companyName": "腾讯",
          "positionName": "C++后台研发工程师", "positionType": "后端开发", "workYear": "5-10年", "education": "本科",
          "jobNature": "全职", "companyShortName": "腾讯科技(北京)有限公司", "city": "北京", "salary": "30k-60k",
          "financeStage": "上市公司", "positionId": 2000527,
          "companyLogo": "image1/M00/10/F6/Cgo8PFT_8gyAHE_VAACEHkeY0jo769.jpg", "positionFirstType": "技术",
          "positionAdvantage": "行业竞争薪酬，业界最好福利，完整发展培训", "approve": 1, "industryField": "移动互联网", "district": "海淀区",
          "score": 0, "companyLabelList": ["节日礼物", "技能培训", "免费娱乐设施", "岗位晋升"], "deliverCount": 0, "leaderName": "马化腾",
          "companySize": "2000人以上", "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0,
          "haveDeliver": false, "imstate": "disabled", "createTimeSort": 1466608942000, "positonTypesMap": null,
          "hrScore": 27, "flowScore": 0, "showCount": 50, "pvScore": 4.686558787510275, "plus": "否",
          "businessZones": ["苏州街", "北京大学", "颐和园"], "publisherId": 5243409, "loginTime": 1466606022000, "appShow": 0,
          "randomScore": 0, "orderBy": 69, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:12:57", "companyId": 70857, "companyName": "八哥科技",
          "positionName": "电话/在线销售", "positionType": "销售", "workYear": "1-3年", "education": "大专", "jobNature": "全职",
          "companyShortName": "北京八哥科技有限责任公司", "city": "北京", "salary": "5k-10k", "financeStage": "初创型(天使轮)",
          "positionId": 1823349, "companyLogo": "image1/M00/42/56/Cgo8PFXLGXCARHJ1AAAxTbvNm60540.png",
          "positionFirstType": "市场与销售", "positionAdvantage": "老板同事 nice、强执行力团队、发展空间大", "approve": 1,
          "industryField": "移动互联网", "district": null, "score": 0, "companyLabelList": ["技能培训", "股票期权", "扁平管理", "美女多"],
          "deliverCount": 0, "leaderName": "暂没有填写", "companySize": "少于15人", "countAdjusted": false, "relScore": 0,
          "adjustScore": 0, "showOrder": 0, "haveDeliver": false, "imstate": "today", "createTimeSort": 1466608377000,
          "positonTypesMap": null, "hrScore": 77, "flowScore": 0, "showCount": 29, "pvScore": 9.607836990779948,
          "plus": "否", "businessZones": null, "publisherId": 1710575, "loginTime": 1466608299000, "appShow": 81,
          "randomScore": 0, "orderBy": 68, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0},
         {"calcScore": false, "createTime": "2016-06-22 23:12:56", "companyId": 70857, "companyName": "八哥科技",
          "positionName": "高级PHP开发工程师", "positionType": "后端开发", "workYear": "3-5年", "education": "本科",
          "jobNature": "全职", "companyShortName": "北京八哥科技有限责任公司", "city": "北京", "salary": "18k-35k",
          "financeStage": "初创型(天使轮)", "positionId": 1080464,
          "companyLogo": "image1/M00/42/56/Cgo8PFXLGXCARHJ1AAAxTbvNm60540.png", "positionFirstType": "技术",
          "positionAdvantage": "福利待遇、发展前景", "approve": 1, "industryField": "移动互联网", "district": "朝阳区", "score": 0,
          "companyLabelList": ["技能培训", "股票期权", "扁平管理", "美女多"], "deliverCount": 0, "leaderName": "暂没有填写",
          "companySize": "少于15人", "countAdjusted": false, "relScore": 0, "adjustScore": 0, "showOrder": 0,
          "haveDeliver": false, "imstate": "today", "createTimeSort": 1466608376000, "positonTypesMap": null,
          "hrScore": 77, "flowScore": 0, "showCount": 29, "pvScore": 4.8960458542449805, "plus": "否",
          "businessZones": ["健翔桥", "小关", "亚运村"], "publisherId": 1710575, "loginTime": 1466608299000, "appShow": 21,
          "randomScore": 0, "orderBy": 68, "formatCreateTime": "1天前发布", "adWord": 0, "totalCount": 0,
          "searchScore": 0.0}]}}}
